# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationRaw',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JobRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('n', models.IntegerField()),
                ('lowerbound', models.FloatField()),
                ('upperbound', models.FloatField()),
                ('suppress', models.BooleanField()),
                ('irrelevant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JobRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MindsumoCellRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.EducationRaw')),
            ],
        ),
        migrations.CreateModel(
            name='MindsumoSample',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SOCEntity',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerQuality',
            fields=[
                ('code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('socentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='careerapp.SOCEntity')),
            ],
            bases=('careerapp.socentity',),
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('socentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='careerapp.SOCEntity')),
            ],
            bases=('careerapp.socentity',),
        ),
        migrations.AddField(
            model_name='mindsumocellraw',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.MindsumoSample'),
        ),
        migrations.AddField(
            model_name='jobrating',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.WorkerQuality'),
        ),
        migrations.AddField(
            model_name='jobrating',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Scale'),
        ),
        migrations.CreateModel(
            name='BroadGroup',
            fields=[
                ('jobgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='careerapp.JobGroup')),
            ],
            bases=('careerapp.jobgroup',),
        ),
        migrations.CreateModel(
            name='MajorGroup',
            fields=[
                ('jobgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='careerapp.JobGroup')),
            ],
            bases=('careerapp.jobgroup',),
        ),
        migrations.CreateModel(
            name='MinorGroup',
            fields=[
                ('jobgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='careerapp.JobGroup')),
                ('super_majorgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.MajorGroup')),
            ],
            bases=('careerapp.jobgroup',),
        ),
        migrations.AddField(
            model_name='mindsumocellraw',
            name='jobcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Job'),
        ),
        migrations.AddField(
            model_name='jobrelation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Job'),
        ),
        migrations.AddField(
            model_name='jobrelation',
            name='relatedJob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_job', to='careerapp.Job'),
        ),
        migrations.AddField(
            model_name='jobrating',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='super_broadgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.BroadGroup'),
        ),
        migrations.AddField(
            model_name='broadgroup',
            name='super_minorgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.MinorGroup'),
        ),
    ]
